coverage:
  status:
    # increase acceptable thresholds for PR checks
    patch:
      default:
        threshold: 1%
    project:
      default:
        threshold: 1%
ignore:
  - "**/*.yaml"
  - "**/*.yml"
  - "**/*.gradle"
  - "**/*.gradle.kts"
  - "build.gradle.kts"